chat:
  replicaCount: 1
  image:
    repository: eyesoncloud/chat-api
    tag: dev
  service:
    type: NodePort
    port: 8000

riskApi:
  replicaCount: 1
  image:
    repository: eyesoncloud/risk-api
    tag: dev
  service:
    type: ClusterIP
    port: 8001

persistence:
  size: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

persistence:
  size: 1Gi
