apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: chat
  ports:
  - port: {{ .Values.chat.service.port }}
    targetPort: {{ .Values.chat.service.port }}
  type: {{ .Values.chat.service.type }}
