apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-api
spec:
  replicas: {{ .Values.riskApi.replicaCount }}
  selector:
    matchLabels:
      app: risk-api
  template:
    metadata:
      labels:
        app: risk-api
    spec:
      containers:
      - name: risk-api
        image: "{{ .Values.riskApi.image.repository }}:{{ .Values.riskApi.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.riskApi.service.port }}
        env:
        - name: APP_ENV
          value: "{{ .Values.riskApi.env.APP_ENV }}"
        - name: MODEL_NAME
          value: "{{ .Values.riskApi.env.MODEL_NAME }}"
        - name: RISK_THRESHOLD
          value: "{{ .Values.riskApi.env.RISK_THRESHOLD }}"
        - name: LOG_DIR
          value: "/shared/logs"
        volumeMounts:
        - name: chat-data
          mountPath: /shared/logs
        resources:
          requests:
            cpu: "{{ .Values.riskApi.resources.requests.cpu }}"
            memory: "{{ .Values.riskApi.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.riskApi.resources.limits.cpu }}"
            memory: "{{ .Values.riskApi.resources.limits.memory }}"
      volumes:
      - name: chat-data
        persistentVolumeClaim:
          claimName: chat-pvc
