apiVersion: v1
kind: Service
metadata:
  name: risk-api
spec:
  selector:
    app: risk-api
  ports:
  - port: {{ .Values.riskApi.service.port }}
    targetPort: {{ .Values.riskApi.service.port }}
  type: {{ .Values.riskApi.service.type }}
