chat:
  replicaCount: 1
  image:
    tag: dev
  service:
    type: NodePort

riskApi:
  replicaCount: 1
  image:
    tag: dev
  service:
    type: NodePort

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

persistence:
  size: 1Gi
